### ISSUE TITLE
CLI Utility

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/v4-migration-tslint#11]
@cwoolum What are your thoughts on making a CLI utility to make it even easier for people to run the linter on their projects? We can use the TSLint API to automatically enable rules and wrap the lint job. Then they would just run something like this:

```
npx ionic-v4-migration
```

**Comment by cwoolum** [comment]
I'm not against it.. I just have no experience with that. The approach I took is the same one RXJS used for their V6 Release.

**Comment by dwieeb** [comment]
The downside is people wouldn't be able to disable rules (unless we add a flag to a tslint config file).

**Comment by dwieeb** [comment]
Update: `tslint` must check for if it's running in a tty, because it doesn't emit output or even fail appropriately when run as a child process, unless I'm missing something. This is basically infeasible.
