### ISSUE TITLE
Provide fixes for *-is-now-an-element rules?

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/v4-migration-tslint#14]
@cwoolum You authored the original `ion-button-is-now-an-element` rule. Is there a reason it does not include a fix? Perhaps because existing markup may include attributes that only `<button>` or `<a>` can deal with?

Can we provide automatic fixes for these rules?

**Comment by cwoolum** [comment]
Yeah, my worry was that there is too much variability and it should be handled on a case-by-case basis. It's too easy for us to break functionality if we do it automatically.

**Comment by j3gb3rt** [comment]
I think this is still valid. With moving from 3 to 4 all instances are broken. It would be nice to at least have this fix the simple cases, like button and a elements with the ion-button attribute. This would heavily cut down on migration time of large applications

**Comment by j3gb3rt** [comment]
@cwoolum If you can point me to a good guide of how to write fixes, I would be willing to take up this task. Just I'm not sure where to start

**Comment by cwoolum** [comment]
[here](https://medium.com/@rokerkony/prevent-coding-mistakes-write-a-tslint-rule-specific-for-your-own-project-987d26f91647) is a medium post on how to do it. It'll give you some high level info on how the rules and fixers work. I pretty much learned by studying the @mgechev/codelyzer repo and replicated a lot of the work there.

**Comment by j3gb3rt** [comment]
Thanks!

**Comment by j3gb3rt** [comment]
PR #58 is up to address this.
