### ISSUE TITLE
ion-segment-button needs ion-label around text now

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/v4-migration-tslint#87]
Can't see this one in the list of rules or planned rules:

## Segment Button
Segment Button text is now required to be wrapped in an ion-label.

**Old usage:**
```
<ion-segment-button>
  Item One
</ion-segment-button>
```

**New usage:**

```
<ion-segment-button>
  <ion-label>Item One</ion-label>
</ion-segment-button>
```

**Comment by dwieeb** [comment]
Thanks, we missed a few rules. Trying to catalog them.

Ref: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#segment-button
